package vn.edu.ut.udm08.shared.model;

public enum MessageType {
    HELLO, HELLO_OK, USER_LIST, CHAT, CHAT_OK, ERROR, DISCONNECT,
    LOGOUT, LOGOUT_OK, SESSION_EXPIRED, SESSION_KICKED,
    HISTORY_REQUEST, HISTORY_RESPONSE,
    CONVERSATION_LIST_REQUEST, CONVERSATION_LIST_RESPONSE,
    USER_SEARCH_REQUEST, USER_SEARCH_RESPONSE,
    OPEN_DM_REQUEST, OPEN_DM_RESPONSE,
    REPLY, FORWARD,
    MESSAGE_ACK
}
