package vn.edu.ut.udm08.shared.model;

public enum MessageType {
    CONVERSATION_READ, CONVERSATION_READ_OK,
    PROFILE_GET, PROFILE_UPDATE, PROFILE_RESPONSE, AVATAR_GET, AVATAR_RESPONSE,
    HELLO, HELLO_OK, USER_LIST, CHAT, CHAT_OK, ERROR, DISCONNECT,
    LOGOUT, LOGOUT_OK, SESSION_EXPIRED, SESSION_KICKED,
    HISTORY_REQUEST, HISTORY_RESPONSE,
    CONVERSATION_LIST_REQUEST, CONVERSATION_LIST_RESPONSE,
    USER_SEARCH_REQUEST, USER_SEARCH_RESPONSE,
    OPEN_DM_REQUEST, OPEN_DM_RESPONSE,
    AUTH_LOGIN, AUTH_LOGIN_OK,
    AUTH_REGISTER_INIT, AUTH_REGISTER_OTP_REQUIRED, AUTH_REGISTER_VERIFY_OTP, AUTH_REGISTER_OK, AUTH_REGISTER_RESEND_OTP,
    AUTH_FORGOT_INIT, AUTH_FORGOT_OTP_REQUIRED, AUTH_FORGOT_RESET, AUTH_FORGOT_OK
}
