package vn.edu.ut.udm08.shared.model;

public enum MessageType {
    HELLO, HELLO_OK, USER_LIST, CHAT, CHAT_OK, ERROR, DISCONNECT,
    LOGOUT, LOGOUT_OK, SESSION_EXPIRED,
    HISTORY_REQUEST, HISTORY_RESPONSE,
    CONVERSATION_LIST_REQUEST, CONVERSATION_LIST_RESPONSE
}


