CREATE TABLE IF NOT EXISTS users (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    phone_number VARCHAR(15) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    avatar_type VARCHAR(10) NOT NULL DEFAULT 'PRESET',
    avatar_path VARCHAR(255) NOT NULL DEFAULT '01.png',
    gender VARCHAR(10) DEFAULT NULL,
    dob DATE DEFAULT NULL,
    bio VARCHAR(255) DEFAULT NULL,
    cover_url VARCHAR(255) DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
